@address = http://localhost:3001
@container_registry = localhost:32000
# @container_registry = registry.localhost:5000
# @container_registry = eu.gcr.io


### Delete pipeline
DELETE {{address}}/delete_pipelines HTTP/1.1

### Create new pipeline actor
POST {{address}}/submit_pipeline_actor HTTP/1.1
content-type: application/json

{
    "name": "demo-pipeline",
    "input_dataset": "test-dataset",
    "input_dataset_commit_hash": "AHDSbHhTrBG3xRdHIo6rWOzzh8NJVowb",
    "fragmenter": {
        "image": "{{ container_registry }}/iterum/demo-fragmenter:latest",
        "output_channel": "edge_detection_input"
    },
    "steps": [
        {
            "name": "edge-detection", 
            "image": "{{ container_registry }}/iterum/demo-edge-detection:latest", 
            "input_channel": "edge_detection_input", 
            "output_channel": "edge_detection_output",
            "config": {
                "H_THRESHOLD1": 100,
                "H_THRESHOLD2": 200
            }
        },
        {
            "name": "hough-transform", 
            "image": "{{ container_registry }}/iterum/demo-hough-transform:latest", 
            "input_channel": "edge_detection_output", 
            "output_channel": "hough_transform_output",
            "config": {
                "BLUR_KERNEL_SIZE": 5
            }
        }
    ],
    "combiner": {
        "input_channel": "hough_transform_output"
    }
}
